version: "3"
services:
  techdojo_db:
    build: ./mysql
    container_name: techdojo_db
    ports:
      - "127.0.0.1:33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: techdojo_db
