CREATE TABLE IF NOT EXISTS `users` (
  `id` INTEGER PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `token` VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS `characters`(
  `id` INTEGER PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) UNIQUE NOT NULL,
  `ratio` FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS `link_user_and_character`(
  `user_id` INTEGER NOT NULL,
  `character_ids` INTEGER NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`character_ids`) REFERENCES `characters` (`id`) ON DELETE CASCADE
);